Repository virtualsatellite/VirtualSatellite4-CEF, pull requests merged in 2019-09, with the labels that each got.

#36 Feature/task 32 ui imporvements category order
  checkStylesDefinition.xml
  de.dlr.sc.virsat.model.extension.cefx.test/src/de/dlr/sc/virsat/model/extension/cefx/hierarchy/CefxHierarchyLevelCheckerTest.java
  de.dlr.sc.virsat.model.extension.cefx.test/src/de/dlr/sc/virsat/model/extension/cefx/test/AllTests.java
  de.dlr.sc.virsat.model.extension.cefx.test/src/de/dlr/sc/virsat/model/extension/cefx/validator/ElementOnMultipleLevelsValidatorTest.java
  de.dlr.sc.virsat.model.extension.cefx.test/src/de/dlr/sc/virsat/model/extension/cefx/validator/WrongHierarchyValidatorTest.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/handler/AddEquipmentMassParametersHandler.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/handler/AddEquipmentParametersHandler.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/handler/AddEquipmentPowerParametersHandler.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/handler/AddEquipmentTemperatureParametersHandler.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/handler/AddSubSystemMassParametersHandler.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/handler/AddSubSystemPowerParametersHandler.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/handler/AddSystemMassParametersHandler.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/handler/AddSystemParametersHandler.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/handler/AddSystemPowerParametersHandler.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetSectionEquipmentMassParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetSectionEquipmentParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetSectionEquipmentPowerParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetSectionEquipmentTemperatureParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetSectionSubSystemMassParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetSectionSubSystemPowerParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetSectionSystemMassParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetSectionSystemParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetSectionSystemPowerParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetTableEquipmentMassParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetTableEquipmentParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetTableEquipmentPowerParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetTableEquipmentTemperatureParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetTableExcelCalculationInputFromExcel.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetTableExcelCalculationOutputToExcel.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetTableSubSystemMassParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetTableSubSystemPowerParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetTableSystemMassParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetTableSystemParameters.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetTableSystemPowerParameters.java
  de.dlr.sc.virsat.model.extension.cefx/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.cefx/plugin.xml
  de.dlr.sc.virsat.model.extension.cefx/src-gen/de/dlr/sc/virsat/model/extension/cefx/ManifestMf.java
  de.dlr.sc.virsat.model.extension.cefx/src/de/dlr/sc/virsat/model/extension/cefx/hierarchy/CefxHierarchyLevel.java
  de.dlr.sc.virsat.model.extension.cefx/src/de/dlr/sc/virsat/model/extension/cefx/hierarchy/CefxHierarchyLevelChecker.java
  de.dlr.sc.virsat.model.extension.cefx/src/de/dlr/sc/virsat/model/extension/cefx/validator/ElementOnMultipleLevelsValidator.java
  de.dlr.sc.virsat.model.extension.cefx/src/de/dlr/sc/virsat/model/extension/cefx/validator/WrongHierarchyValidator.java
Labels: comfort/usasbility

#37 Cleaned up travis yml file and prepared for xenial
  .settings/org.eclipse.core.resources.prefs
  .settings/org.eclipse.core.runtime.prefs
  .travis.yml
  bash/deploy_sourceforge.sh
  bash/maven_build.sh
  bash/setup_environment.sh
  de.dlr.sc.virsat.cef.branding.feature/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.cef.branding.ui/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.cef.calculation.test/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.cef.calculation/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.cef.docs.feature/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.cef.license.feature/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.cef.p2updatesite/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.cef.product/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.cef.target.feature/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.cef.target/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.cef.target/tmodel-src/virsat_cef_development.tmodel
  de.dlr.sc.virsat.cef.target/virsat_cef_integration.target
  de.dlr.sc.virsat.cef.target/virsat_cef_release.target
  de.dlr.sc.virsat.cef.test.feature/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.cef.test/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.model.extension.cef.feature/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.model.extension.cef.interfaces.feature/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.model.extension.cef.interfaces.test/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.model.extension.cef.interfaces.ui/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.model.extension.cef.interfaces/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.model.extension.cef.test/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.model.extension.cef.ui/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.model.extension.cef/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.model.extension.cefx.feature/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.model.extension.cefx.test/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.model.extension.cefx.ui/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.model.extension.cefx/.settings/org.eclipse.core.runtime.prefs
  maven/pom.xml
Labels: build

#43 Fixing deployment script - (Task #42)
  bash/deploy_sourceforge.sh
Labels: bug, build

#41 Updated product definition - (Task #40)
  de.dlr.sc.virsat.cef.product/virsat_cef.product
Labels: bug, build
