Repository virtualsatellite/VirtualSatellite4-CEF, pull requests merged in 2020-04, with the labels that each got.

#100 Fixed NPE in getGLobalQuantity for Development Build Fail
  de.dlr.sc.virsat.model.extension.cef.interfaces.ui/src/de/dlr/sc/virsat/model/extension/cef/interfaces/ui/decorator/InterfaceEndQuantityKindDecorator.java
  de.dlr.sc.virsat.model.extension.cef.interfaces/src/de/dlr/sc/virsat/model/extension/cef/interfaces/model/AInterfaceEnd.java
  de.dlr.sc.virsat.model.extension.cef.ui/src/de/dlr/sc/virsat/model/extension/cef/ui/decorator/QuantityKindDecorator.java
  de.dlr.sc.virsat.model.extension.cef/src/de/dlr/sc/virsat/model/extension/cef/model/EquipmentParameters.java
Labels: bug, build, easy

#103 Updated License information
  NOTICE.md
  de.dlr.sc.virsat.cef.branding.ui/about.html
  de.dlr.sc.virsat.cef.branding.ui/plugin.xml
  de.dlr.sc.virsat.cef.docs.feature/docs/LICENSE
  de.dlr.sc.virsat.cef.docs.feature/docs/NOTICE.md
  de.dlr.sc.virsat.cef.product/virsat_cef.product
Labels: bug, quality, release

#104 Feature/task 94 swt bot stub in vir sat
  de.dlr.sc.virsat.cef.swtbot.test/.checkstyle
  de.dlr.sc.virsat.cef.swtbot.test/.classpath
  de.dlr.sc.virsat.cef.swtbot.test/.project
  de.dlr.sc.virsat.cef.swtbot.test/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.cef.swtbot.test/.settings/org.eclipse.core.resources.prefs
  de.dlr.sc.virsat.cef.swtbot.test/.settings/org.eclipse.jdt.core.prefs
  de.dlr.sc.virsat.cef.swtbot.test/.settings/org.eclipse.m2e.core.prefs
  de.dlr.sc.virsat.cef.swtbot.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.cef.swtbot.test/about.html
  de.dlr.sc.virsat.cef.swtbot.test/build.properties
  de.dlr.sc.virsat.cef.swtbot.test/pom.xml
  de.dlr.sc.virsat.cef.swtbot.test/src/de/dlr/sc/virsat/cef/swtbot/test/ProjectUiAllTest.java
  de.dlr.sc.virsat.cef.swtbot.test/src/de/dlr/sc/virsat/cef/swtbot/test/SWTBotTestCaseStub.java
  known_authors.txt
  pom.xml
Labels: quality
