Repository virtualsatellite/VirtualSatellite4-CEF, pull requests merged in 2020-01, with the labels that each got.

#60 Adjusted Checkstyle Settings with latest of Core
  checkStylesDefinition.xml
  de.dlr.sc.virsat.model.extension.cef.interfaces.ui/src/de/dlr/sc/virsat/model/extension/cef/interfaces/ui/snippet/UiSnippetTableEquipmentDataParameters.java
  de.dlr.sc.virsat.model.extension.cef.interfaces/concept/concept.concept
  de.dlr.sc.virsat.model.extension.cef.ui/src/de/dlr/sc/virsat/model/extension/cef/ui/decorator/QuantityKindDecorator.java
  de.dlr.sc.virsat.model.extension.cefx/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.cefx/concept/concept_v1_0.xmi
  de.dlr.sc.virsat.model.extension.cefx/plugin.xml
  maven/pom.xml
Labels: bug, build

#51 Feature/task 10 margin of nested eqipments
  de.dlr.sc.virsat.model.extension.cef.test/src-gen/de/dlr/sc/virsat/model/extension/cef/migrator/AMigrator1v6Test.java
  de.dlr.sc.virsat.model.extension.cef.test/src-gen/de/dlr/sc/virsat/model/extension/cef/test/AllTestsGen.java
  de.dlr.sc.virsat.model.extension.cef.test/src/de/dlr/sc/virsat/model/extension/cef/migrator/Migrator1v6Test.java
  de.dlr.sc.virsat.model.extension.cef/concept/concept.concept
  de.dlr.sc.virsat.model.extension.cef/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.cef/concept/concept_v1_6.xmi
  de.dlr.sc.virsat.model.extension.cef/plugin.xml
  de.dlr.sc.virsat.model.extension.cef/src-gen/de/dlr/sc/virsat/model/extension/cef/PluginXml.java
  de.dlr.sc.virsat.model.extension.cef/src-gen/de/dlr/sc/virsat/model/extension/cef/migrator/AMigrator1v6.java
  de.dlr.sc.virsat.model.extension.cef/src/de/dlr/sc/virsat/model/extension/cef/migrator/Migrator1v6.java
  de.dlr.sc.virsat.model.extension.cefx/concept/concept.concept
  de.dlr.sc.virsat.model.extension.cefx/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.cefx/concept/concept_v1_0.xmi
Labels: bug

#71 Updated jacoco addresses in build script - (Task #70)
  build.xml
Labels: build

#73 Added drop adapter to plugin xml of PT View in CEFX
  de.dlr.sc.virsat.model.extension.cefx.ui/plugin.xml
Labels: bug, easy, feature

#67 Fix deep nesting in CEF-X Mass Summaries
  de.dlr.sc.virsat.cef.target/virsat_cef_development.target
  de.dlr.sc.virsat.model.extension.cef.interfaces/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.cef.interfaces/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.model.extension.cef.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.cef/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.cef/concept/concept_v1_5.xmi
  de.dlr.sc.virsat.model.extension.cef/concept/concept_v1_6.xmi
  de.dlr.sc.virsat.model.extension.cefx.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/masssummary/MassSummaryView.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/masssummary/UiSnippetElements.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/snippet/UiSnippetSectionDocument.java
  de.dlr.sc.virsat.model.extension.cefx/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.cefx/concept/concept_v1_0.xmi
  de.dlr.sc.virsat.model.extension.cefx/src-gen/de/dlr/sc/virsat/model/extension/cefx/migrator/AMigrator1v1.java
  de.dlr.sc.virsat.model.extension.cefx/src-gen/de/dlr/sc/virsat/model/extension/cefx/migrator/AMigrator1v2.java
  de.dlr.sc.virsat.model.extension.cefx/src-gen/de/dlr/sc/virsat/model/extension/cefx/migrator/AMigrator1v3.java
  de.dlr.sc.virsat.model.extension.cefx/src-gen/de/dlr/sc/virsat/model/extension/cefx/migrator/AMigrator1v4.java
  de.dlr.sc.virsat.model.extension.cefx/src-gen/de/dlr/sc/virsat/model/extension/cefx/migrator/AMigrator1v5.java
Labels: feature

#76 Updated target platform and product - (Task #75)
  de.dlr.sc.virsat.cef.product/virsat_cef.product
  de.dlr.sc.virsat.cef.target/virsat_cef_development.target
  launch/VirSat CEF Application (user).launch
Labels: build

#78 Fixed references to DVLMDelegateDropAdapterAssistant
  de.dlr.sc.virsat.model.extension.cefx.ui/plugin.xml
Labels: quality
