Repository virtualsatellite/VirtualSatellite4-CEF, pull requests merged in 2020-02, with the labels that each got.

#79 Remove auto generated files from PR
  .gitattributes
Labels: build, easy

#81 Improved deployment to sourceforge
  .travis.yml
  bash/deploy_sourceforge.sh
  bash/maven_build.sh
  bash/ssh-add-password.sh
  id_ed25519.enc
Labels: build

#95 Cleaned up ModeTableView class - (Task #84)
  de.dlr.sc.virsat.model.extension.cefx.test/src/de/dlr/sc/virsat/model/extension/cefx/util/CefModeHelperTest.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/modesview/ModeHelper.java
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/modesview/ModeTableView.java
  de.dlr.sc.virsat.model.extension.cefx/src/de/dlr/sc/virsat/model/extension/cefx/util/CefModeHelper.java
Labels: bug, ui

#96 Feature/task 91 npe when adding only s
  de.dlr.sc.virsat.model.extension.cefx.ui/src/de/dlr/sc/virsat/model/extension/cefx/ui/masssummary/UiSnippetSystem.java
Labels: bug

#97 New CEFx icon - (Task #85)
  de.dlr.sc.virsat.model.extension.cefx.ui/resources/icons/Cefx.gif
  de.dlr.sc.virsat.model.extension.cefx.ui/resources/icons/de.dlr.sc.virsat.model.extension.cefx.gif
  de.dlr.sc.virsat.model.extension.cefx.ui/resources/icons/de.dlr.sc.virsat.model.extension.cefx_disabled.gif
Labels: ui
